spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d34ca268b7dba9
    password: ff991d3b0ffc1f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp
  datasource:
#    [Para DB Externa]
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demeter?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password:

#    [InMemory DB]
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

    initialization-mode: always
  jpa:
#    [InMemory DB]
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
jwt:
  expiration:
    time: 90000